#!/usr/bin/env zsh


# This is actually a zsh script.; don't tell anyone. I guess it depends on
# how you want to interpret which kind of "script" this is. It is definitely
# an awk script if you ignore the shebang and the next lines

exec awk -f <(sed '1,/^#__AWK__$/d' "$0") -- "$@"
# ^-- This is to pass -h and --help to the script without passing it to awk directly
# v-- sed will delete up to this next line and feed the rest of the file to awk (:
#__AWK__


# Read the output of NUMCBAS -> GTOBAS codes, which poduce files like
#   # Function 1
#   x   ygauss   ynum
#   x   ygauss   ynum
#   x   ygauss   ynum
#   x   ygauss   ynum
#   # Function 2
#   x   ygauss   ynum
#   x   ygauss   ynum
#   x   ygauss   ynum
#   x   ygauss   ynum
#
# Where ygauss is a gaussian fit to the numerical solution ynum for continuum functions.
# This script prints the relative difference of each function and the total relative difference.
# Column 1 is ignored

function usage() {
  print "Usage:\n\n" \
        "    gtobas_refldiff FILE\n\n" \
        "Print the per-function and total relative differences of numerical continuum functions\n" \
        "and gaussian fits to those functions.\n\n" \
        "`NUMCBAS` is used to determine numerical continuum solutions in electron-molecule\n" \
        "scattering problems. `GTOBAS` finds gaussian fits to these. When chained together,\n" \
        "`NUMCBAS` -> `GTOBAS` writes to file descriptor 13, producing the file `fort.13`,\n" \
        "which contains the functions contatenated as follows:\n\n" \
        "    # Function 1\n" \
        "    x  ygauss  ynum\n" \
        "    x  ygauss  ynum\n" \
        "    ...............\n" \
        "    # Function 2\n" \
        "    x  ygauss  ynum\n" \
        "    x  ygauss  ynum\n" \
        "    ...............\n\n" \
        "Options:\n\n" \
        "    -h, --help     show this help message"
}

function print_fres() {
  if(!seen_function || n < 1) { return }
  printf "%s resl_L2 = %.8e\n", fname, sqrt(ferr2 / fref2)
}

function set_max_fres() {
  if(!seen_function || n < 1) { return }
  fres_L2 = fref2 > 0 ? sqrt(ferr2 / fref2) : "0.0"
  if(fres_L2 > max_resl_L2) { max_resl_L2 = fres_L2 }
}

function print_max_fres() {
  if(!seen_function || n < 1) { return }
  return (max_resl_L2 > 0) ? sprintf("%.8e", max_resl_L2) : "NaN"
}

function print_rel_l2(err2, ref2) {
  return (ref2 > 0) ? sprintf("%.8e", sqrt(err2 / ref2)) : "NaN"
}

BEGIN {
  skip_end = 0
  for (i=1; i < ARGC; i++) {
    if (ARGV[i] == "-h" || ARGV[i] == "--help") {
      usage()
      skip_end = 1
      exit 0
    }
  }
  total_err2 = 0
  total_ref2 = 0
  max_resl_L2 = 0
  seen_function = 0
  ntot=0
  n=0
  ferr2 = 0
  fres2 = 0
  seen_function=0
}

# -- New function block
/^[[:space:]]#[[:space:]]Function/ {
  print_fres()
  set_max_fres()

  fname = $0
  ferr2 = 0
  fref2 = 0
  n = 0
  seen_function=1
  next
}

# -- Data format:
# x    yfit    ynum
seen_function && NF >= 3 {
  gauss = $2
  sol = $3
  diff = gauss - sol
  ferr2 += diff  * diff
  fref2 += sol   * sol
  total_err2 += diff  * diff
  total_ref2 += sol   * sol

  n++
  ntot++
}

END {
  if (skip_end) { exit 0 }
  print_fres()
  print "TOTAL:"
  printf "  npoints = %d\n", ntot
  printf "  total resl_L2 = %s\n", print_rel_l2(total_err2, total_ref2)
  printf "  max individual resl_L2 = %s\n", print_max_fres()

}
